import AppKit
import AnywhereDoCore

struct ClipboardEvent {
    let text: String
    let sourceAppName: String?
    let sourceBundleID: String?
    let isSensitive: Bool
}

/// 剪贴板没有系统通知，只能靠 changeCount 轮询。
/// 只在 changeCount 变化时才真正读取内容，尽可能少触发系统粘贴权限提示。
final class PasteboardWatcher {
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int
    private let interval: TimeInterval

    var onEvent: ((ClipboardEvent) -> Void)?
    var isPaused = false

    /// 密码管理器等会打上这些类型标记，遇到就跳过。
    static let sensitiveTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("com.typeit4me.clipping"),
    ]

    init(interval: TimeInterval = 0.35) {
        self.interval = interval
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        stop()
        // 启动瞬间同步一次，避免把启动前的内容当成新复制。
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        timer.tolerance = interval / 3
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// 我们自己写剪贴板后调用，避免把自己的写入当成用户复制。
    func acknowledgeCurrentChange() {
        lastChangeCount = pasteboard.changeCount
    }

    private func poll() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        guard !isPaused else { return }

        let types = pasteboard.types ?? []
        let sensitive = types.contains { Self.sensitiveTypes.contains($0) }
        guard let text = Self.readText(from: pasteboard, types: types) else { return }

        let frontmost = NSWorkspace.shared.frontmostApplication
        let event = ClipboardEvent(
            text: text,
            sourceAppName: frontmost?.localizedName,
            sourceBundleID: frontmost?.bundleIdentifier,
            isSensitive: sensitive
        )
        onEvent?(event)
    }

    /// 普通文本优先；在 Finder 里复制文件时，剪贴板里只有文件 URL。
    static func readText(from pasteboard: NSPasteboard, types: [NSPasteboard.PasteboardType]) -> String? {
        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            return string
        }
        if types.contains(.fileURL) {
            let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
            if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
               let first = urls.first {
                // 多选时只取第一个：路径要能直接被识别成文件路径。
                return first.path
            }
        }
        return nil
    }
}
